title: "Second Shift Curriculum - Turing School of Software and Design"
description: "Open source curriculum for the Turing School of Software and Design's second shift program."
url: "https://turingschool.github.io/second_shift"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/blank/assets'

images:
  root_url: '/blank/assets/images'

plugins:
  - jemoji
